#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  Neural-Nexus  ·  C2 Machine Setup  (run once)
#
#  Architecture:
#    ┌─────────────────────────────┐   ┌─────────────────────────────────────┐
#    │  C2 Machine  (this script)  │   │  Victim Machine  (separate host)    │
#    │  • C2 server (port 5001)    │   │  • victim-lab app (port 8080)       │
#    │  • File server (port 8001)  │   │  • Ollama LLM (port 11434)          │
#    │  → run: ./start-c2.sh       │   │  → run: ./start-demo.sh on victim   │
#    └─────────────────────────────┘   └─────────────────────────────────────┘
#
#  This script prepares the C2 machine ONLY:
#    • Verifies Python 3 prerequisite
#    • Creates a Python venv for the C2 server
#    • Installs C2 Python dependencies
#    • Generates the C2 launcher (server/start-c2-server.sh)
#
#  Usage:
#    chmod +x setup.sh
#    ./setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GRN='\033[0;32m'; YEL='\033[1;33m'
CYN='\033[0;36m'; PRP='\033[0;35m'; BLD='\033[1m'; RST='\033[0m'

ok()   { echo -e "${GRN}  ✓${RST}  $*"; }
info() { echo -e "${CYN}  ●${RST}  $*"; }
warn() { echo -e "${YEL}  ⚠${RST}  $*"; }
fail() { echo -e "${RED}  ✗  $*${RST}"; exit 1; }
step() { echo -e "\n${BLD}${PRP}▶ $*${RST}"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
C2_DIR="$SCRIPT_DIR/server"
VENV="$SCRIPT_DIR/.venv"

for arg in "$@"; do
  case "$arg" in
    --help|-h)
      echo ""; echo "  Usage: ./setup.sh"
      echo "  Sets up the C2 machine Python environment."
      echo "  The victim lab runs separately on another host."; echo ""
      exit 0 ;;
    *) warn "Unknown argument: $arg (ignored)" ;;
  esac
done

# ── Banner ────────────────────────────────────────────────────────────────────
clear
echo -e "${PRP}"
cat << 'BANNER'
  ███╗   ██╗███████╗██╗   ██╗██████╗  █████╗ ██╗         ███╗   ██╗███████╗██╗  ██╗██╗   ██╗███████╗
  ████╗  ██║██╔════╝██║   ██║██╔══██╗██╔══██╗██║         ████╗  ██║██╔════╝╚██╗██╔╝██║   ██║██╔════╝
  ██╔██╗ ██║█████╗  ██║   ██║██████╔╝███████║██║         ██╔██╗ ██║█████╗   ╚███╔╝ ██║   ██║███████╗
  ██║╚██╗██║██╔══╝  ██║   ██║██╔══██╗██╔══██║██║         ██║╚██╗██║██╔══╝   ██╔██╗ ██║   ██║╚════██║
  ██║ ╚████║███████╗╚██████╔╝██║  ██║██║  ██║███████╗    ██║ ╚████║███████╗██╔╝ ██╗╚██████╔╝███████║
  ╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝    ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
BANNER
echo -e "${RST}"
echo -e "  ${BLD}C2 Machine Setup${RST}"
echo -e "  ${YEL}──────────────────────────────────────────────${RST}\n"
echo -e "  ${CYN}Architecture:${RST}  Two-machine split"
echo -e "  ${CYN}This machine:${RST}  C2 server + HTTP file server"
echo -e "  ${CYN}Victim machine:${RST} victim-lab app + Ollama LLM  ${YEL}(run start-demo.sh there)${RST}\n"

cd "$SCRIPT_DIR"

# ─────────────────────────────────────────────────────────────────────────────
# 1. PREREQUISITES
# ─────────────────────────────────────────────────────────────────────────────
step "Checking prerequisites"

# Python 3
if command -v python3 &>/dev/null; then
  PY_VER=$(python3 --version)
  PY_MINOR=$(python3 -c "import sys; print(sys.version_info.minor)")
  (( PY_MINOR < 8 )) && fail "Python 3.8+ required  (found: $PY_VER)"
  ok "$PY_VER"
else
  fail "python3 not found  →  apt install python3"
fi

# pip / venv
if ! python3 -m venv --help &>/dev/null; then
  PY_MINOR=$(python3 -c "import sys; print(sys.version_info.minor)")
  fail "python3-venv not installed  →  apt install python3.${PY_MINOR}-venv"
fi
ok "python3-venv available"

# ─────────────────────────────────────────────────────────────────────────────
# 2. PYTHON VENV FOR C2
# ─────────────────────────────────────────────────────────────────────────────
step "Setting up Python environment for the C2 server"

if [[ ! -f "$VENV/bin/activate" ]]; then
  info "Creating venv at $VENV ..."
  python3 -m venv "$VENV"
  ok "venv created"
else
  ok "venv already exists at $VENV"
fi

info "Upgrading pip..."
"$VENV/bin/pip" install -q --upgrade pip

if [[ -f "$C2_DIR/requirements.txt" ]]; then
  info "Installing C2 dependencies (server/requirements.txt)..."
  "$VENV/bin/pip" install -q -r "$C2_DIR/requirements.txt"
  ok "Python dependencies installed"
else
  warn "server/requirements.txt not found — skipping"
fi

# Generate C2 launcher if it doesn't exist
C2_LAUNCHER="$C2_DIR/start-c2-server.sh"
if [[ ! -f "$C2_LAUNCHER" ]]; then
  info "Generating $C2_LAUNCHER ..."
  cat > "$C2_LAUNCHER" << 'LAUNCHER'
#!/usr/bin/env bash
# C2 Server launcher — generated by setup.sh
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
VENV="$ROOT_DIR/.venv"
C2_PORT="${C2_PORT:-5001}"

[[ ! -f "$VENV/bin/activate" ]] && echo "ERROR: venv not found. Run ./setup.sh first." && exit 1

echo -e "\n  \033[0;35m▶ Starting C2 server on port ${C2_PORT}\033[0m"
echo -e "  \033[0;36m●\033[0m Panel: http://localhost:${C2_PORT}\n"

cd "$SCRIPT_DIR"
PORT="$C2_PORT" "$VENV/bin/python" app.py
LAUNCHER
  chmod +x "$C2_LAUNCHER"
  ok "Launcher created: server/start-c2-server.sh"
else
  ok "server/start-c2-server.sh already exists"
fi

# ─────────────────────────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
echo -e "\n${BLD}${GRN}  ══════════════════════════════════════════════════${RST}"
echo -e "${BLD}${GRN}  ✓  C2 setup complete${RST}"
echo -e "${BLD}${GRN}  ══════════════════════════════════════════════════${RST}\n"

LAN_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' || hostname -I 2>/dev/null | awk '{print $1}' || echo "<C2_IP>")

echo -e "  ${BLD}Next steps:${RST}\n"
echo -e "  ${PRP}① Start the C2 + file server on this machine:${RST}"
echo -e "     ${YEL}./start-c2.sh${RST}"
echo -e "     ${CYN}→ C2 panel:   http://localhost:5001${RST}"
echo -e "     ${CYN}→ File server: http://${LAN_IP}:8001${RST}\n"
echo -e "  ${PRP}② On the victim machine, configure and start the victim lab:${RST}"
echo -e "     ${YEL}./start-demo.sh${RST}  ${CYN}(set NN_C2=http://${LAN_IP}:5001 on that machine)${RST}\n"
echo -e "  ${PRP}③ Attack flow:${RST}"
echo -e "     ${CYN}a)${RST} Victim visits the CorpAI app → installs Neural Nexus skill"
echo -e "     ${CYN}b)${RST} Agent connects to C2 → appears in panel"
echo -e "     ${CYN}c)${RST} Run AutoRecon → discovers victim-lab at victim's IP:8080"
echo -e "     ${CYN}d)${RST} Launch AI Hunter → prompt injection / credential exfil"
echo -e "     ${CYN}e)${RST} C2 auto-detects SMB credentials → suggests lateral movement\n"
